package hacktip.demo.domain;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * JPA Entity: 'POSTS' 테이블
 * (사용자의 Member.java와 호환되도록 FK(author)가 수정됨)
 */
@Data
@NoArgsConstructor
@Entity
@Table(name = "POSTS") // DDL의 'POSTS' 테이블 이름 사용
public class Post {

    // DDL: POST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "POST_ID")
    private Long postId;

    // --- [수정된 핵심 FK] ---
    /**
     * 작성자 (Member 엔티티 참조)
     * DDL의 POSTS.AUTHOR_ID (VARCHAR2) 대신,
     * 실제 Member.java (MEMBERS.MEMBERID (Long))를 참조합니다.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    // DDL의 컬럼명 'AUTHOR_ID'를 그대로 사용하되,
    // JPA가 이 컬럼에 Member의 PK(Long memberId)를 저장하도록 매핑
    @JoinColumn(name = "AUTHOR_ID", nullable = false)
    private Member author;
    // --- (이전 코드: private String authorId;) ---

    // DDL: TITLE VARCHAR2(1000) NOT NULL
    @Column(name = "TITLE", nullable = false, length = 1000)
    private String title;

    // DDL: CONTENT CLOB NOT NULL
    @Lob
    @Column(name = "CONTENT", nullable = false, columnDefinition = "CLOB")
    private String content;

    // DDL: CATEGORY VARCHAR2(100) NOT NULL
    @Column(name = "CATEGORY", nullable = false, length = 100)
    private String category;

    // DDL: POST_TYPE VARCHAR2(50) NOT NULL
    @Column(name = "POST_TYPE", nullable = false, length = 50)
    private String postType;

    // DDL: PORTFOLIO_LINK VARCHAR2(1000)
    @Column(name = "PORTFOLIO_LINK", length = 1000)
    private String portfolioLink;

    // DDL: CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
    @CreationTimestamp
    @Column(name = "CREATED_AT", nullable = false, updatable = false)
    private Instant createdAt;

    // DDL: VIEWS NUMBER DEFAULT 0
    @Column(name = "VIEWS", nullable = false)
    private int views = 0;

    // DDL: IS_RESOLVED CHAR(1) DEFAULT 'N'
    @Column(name = "IS_RESOLVED", nullable = false)
    private char isResolved = 'N';

    // DDL: IS_HIRED_SUCCESS CHAR(1) DEFAULT 'N'
    @Column(name = "IS_HIRED_SUCCESS", nullable = false)
    private char isHiredSuccess = 'N';
}